steps:
- name: "gcr.io/cloud-builders/docker"
  entrypoint: "bash"
  args:
  - "-c"
  - |
      echo $COMMIT_SHA
      for SERVICE in  "frontend" "contacts" "userservice" "accounts-db" "loadgenerator"; do
        IMAGE_PATH="gcr.io/${PROJECT_ID}/bank-of-anthos/frontend:${COMMIT_SHA}"
        echo "building $$IMAGE_PATH"
        docker build -t $$IMAGE_PATH src/$$SERVICE
        docker push $$IMAGE_PATH
      done
- id: "create-attestation"
  name: "gcr.io/${PROJECT_ID}/binauthz-attestation:latest"
  args:
    - "--artifact-url"
    - "gcr.io/${PROJECT_ID}/bank-of-anthos/frontend:${COMMIT_SHA}"
    - "--attestor"
    - "projects/${PROJECT_ID}/attestors/manual-attestor"
    - "--keyversion"
    - "projects/${PROJECT_ID}/locations/global/keyRings/bank-of-anthos-binauthz-keys/cryptoKeys/manual-key/cryptoKeyVersions/1"
